<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tplpre</string>
	</array>
	<key>name</key>
	<string>tplpre</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#doc_strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment_TODO_line</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment_line</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#metadata_2</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#overwiev</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#simple_identifiers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#if_addm</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.character.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>tpl\s+?(\$\$TPLVERSION\$\$|\d+\.\d+)\s+?module\s(.*);</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.tplpre</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tplpre</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>from\s(\w+)(?:\.(\w+))?(?:\.(\w+))?\simport\s(\S+)\s(\d+(?:\.\d+)+);</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(configuration)\s(\S+)\s(\d+\.\d+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.tplpre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(end\sconfiguration;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#doc_strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lines</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#if_addm</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(table)\s(\S+)\s(\d+(?:\.\d+)+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.tplpre</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>comment.block.documentation.tplpre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(end\stable;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>comment.block.documentation.tplpre</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(definitions)\s(\S+)\s(\d+(?:\.\d+)+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.tplpre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(end\sdefinitions;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#doc_strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#define</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#alt_define</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lines</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#if_addm</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\b(pattern)\s+(\w+)\s(\d+(?:\.\d+)+)\s+$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.tplpre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\b(end\spattern;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#doc_strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#metadata</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#overwiev</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#triggers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#removal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#body</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#if_addm</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>ConversionFunctions</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.accessor.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(ConversionFunctions)(\.)(isValidSerialNumber|convertToCharString|convertToBytes)</string>
		</dict>
		<key>DiscoveryFunctions</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.accessor.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(DiscoveryFunctions)(\.)(pathNormalization|getCleanedupPath|getMaxVersion|getExeCwdPath|sortList|runActiveCommand|locateCommands|checkCommandList)</string>
		</dict>
		<key>RDBMSFunctions</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.accessor.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(RDBMSFunctions)(\.)(oracleOraFileParser|performRdbmsSisSearch|oracleNetServiceNameSearch|dsnRdbmsServers|parseJDBC)</string>
		</dict>
		<key>SearchFunctions</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.accessor.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(SearchFunctions)(\.)(getNodeIp|getHostingNodes|getSoftwareNodes|getSI|identifyHostWithUuid|relatedSisSearchOnMultipleHosts)</string>
		</dict>
		<key>all_controls</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#if_statement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#elif_statement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#then_statement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#else_statement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#end_if_statement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#for_statement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#end_for_statement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#if_addm</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords_all</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords_cmd</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#all_keys</string>
				</dict>
			</array>
		</dict>
		<key>all_functions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#xpath</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#discovery_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#model_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#model_SI_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#model_rel_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#log_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#log_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#text_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regex_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#xpath_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#discovery_manipulation_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#binary_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#json_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#related_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#mail_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#time_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inference_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ConversionFunctions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#SearchFunctions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rdbms_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#RDBMSFunctions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#DiscoveryFunctions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#common_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#local_functions</string>
				</dict>
			</array>
		</dict>
		<key>all_keys</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#var_assign</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#index_assign</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#square_brackets</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#equal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#less</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#more</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#more_equal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#less_equal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#plus</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#divide</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#decimal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#minus_decimal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#just_do</string>
				</dict>
			</array>
		</dict>
		<key>alt_define</key>
		<dict>
			<key>begin</key>
			<string>\s+(define)\s+(\S+)(\s\S+\s(.*))?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.tplpre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\s+(end\sdefine;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
			</dict>
			<key>name</key>
			<string>alt_define.complex.tplpre</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#doc_strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#all_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lines</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#all_controls</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#if_addm</string>
				</dict>
			</array>
		</dict>
		<key>binary_functions</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.accessor.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.constant.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(binary)(\.)(toHexString|toIPv4|toIPv4z|toIPv6|toIPv6z|toMACAddress|toValue|toWWN)</string>
		</dict>
		<key>body</key>
		<dict>
			<key>begin</key>
			<string>^\s{4}(body)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^\s{4}(end\sbody;)$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
			</dict>
			<key>name</key>
			<string>body.complex.tplpre</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#doc_strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lines</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#all_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#all_controls</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#if_addm</string>
				</dict>
			</array>
		</dict>
		<key>comment_TODO_line</key>
		<dict>
			<key>begin</key>
			<string>(//)\s?(TODO\:)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>variable.parameter.tplpre</string>
			<key>end</key>
			<string>(.*)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.tplpre</string>
				</dict>
			</dict>
		</dict>
		<key>comment_line</key>
		<dict>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.line.tplpre</string>
		</dict>
		<key>common_functions</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.accessor.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(functions)(\.)(validate_host_address_format|domain_lookup|identify_host_perform_search|identify_host_perform_search_in_scope|identify_host|identify_host_extended|related_sis_search\b|related_sis_search_on_multiple_hosts|related_sis_search_on_multiple_hosts_extended|related_sis_search_extended|related_si_types_search|path_normalization|links_management|get_cleanedup_path|get_max_version|get_exe_cwd_path|sort_list|run_priv_cmd|has_process|isValidSerialNumber|convertToCharString|wmiFollowAssociations|checkForDecimal|convertToBytes|identify_host_with_uuid|locateCommands|find_server|checkCommandList)</string>
		</dict>
		<key>constants</key>
		<dict>
			<key>begin</key>
			<string>\b(constants)\s+?$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\b(end\sconstants;)\s+?$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
			</dict>
			<key>name</key>
			<string>constants.complex.tplpre</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#lines</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#all_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#if_addm</string>
				</dict>
			</array>
		</dict>
		<key>content_raw</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s\b(raw)\s+</string>
		</dict>
		<key>decimal</key>
		<dict>
			<key>match</key>
			<string>\s\d+\s</string>
			<key>name</key>
			<string>constant.numeric.integer.tplpre</string>
		</dict>
		<key>define</key>
		<dict>
			<key>begin</key>
			<string>\s+(define)\s+(\S+)\((.*?)\)(\s\S+\s(.*))?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.tplpre</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.tplpre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\s+(end\sdefine;\s+?$)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
			</dict>
			<key>name</key>
			<string>define.complex.tplpre</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#doc_strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#all_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lines</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#all_controls</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#if_addm</string>
				</dict>
			</array>
		</dict>
		<key>discovery_functions</key>
		<dict>
			<key>begin</key>
			<string>(discovery)(\.)(fileGet|fileInfo|getNames|listDirectory|listRegistry|registryKey|wmiQuery|wbemQuery|wbemEnumInstances|runCommand|snmpGet|snmpGetTable|restfulGet|restfulPost|vSphereFindObjects|vSphereTraverseToObjects|vSphereGetProperties|vSphereGetPropertyTable)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.accessor.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.constant.tplpre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\;</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>disabled.tplpre</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#lines</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#all_controls</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regex</string>
				</dict>
			</array>
		</dict>
		<key>discovery_manipulation_functions</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.accessor.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.constant.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(discovery)(\.)(process|children|descendents|parent|allProcesses|access)</string>
		</dict>
		<key>doc_strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#doc_strings_block_doulbe_q</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#doc_strings_block_single_q</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#doc_strings_single_simple</string>
				</dict>
			</array>
		</dict>
		<key>doc_strings_block_doulbe_q</key>
		<dict>
			<key>begin</key>
			<string>(\"{3})</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.block.documentation.tplpre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\"{3})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.block.documentation.tplpre</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.tplpre</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.block.documentation.tplpre</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\d{2,4}\-\d{2,4}\-\d{2,4})(.*)?(\d{2,4}\-\d{2,4}\-\d{2,4})?</string>
					<key>name</key>
					<string>variable.parameter.tplpre</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>comment.block.documentation.tplpre</string>
				</dict>
			</array>
		</dict>
		<key>doc_strings_block_single_q</key>
		<dict>
			<key>begin</key>
			<string>('{3})</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.block.documentation.tplpre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>('{3})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.block.documentation.tplpre</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.tplpre</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.block.documentation.tplpre</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\d{2,4}\-\d{2,4}\-\d{2,4})(.*)?(\d{2,4}\-\d{2,4}\-\d{2,4})?</string>
					<key>name</key>
					<string>variable.parameter.tplpre</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>comment.block.documentation.tplpre</string>
				</dict>
			</array>
		</dict>
		<key>doc_strings_single_simple</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.triple.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.triple.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.quoted.triple.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>('{3}([^']+?)'{3})</string>
			<key>name</key>
			<string>comment.block.documentation.tplpre</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.tplpre</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.block.documentation.tplpre</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\d{2,4}\-\d{2,4}\-\d{2,4})(.*)?(\d{2,4}\-\d{2,4}\-\d{2,4})?</string>
					<key>name</key>
					<string>variable.parameter.tplpre</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>comment.block.documentation.tplpre</string>
				</dict>
			</array>
		</dict>
		<key>double_q</key>
		<dict>
			<key>match</key>
			<string>(\"\"){1}</string>
			<key>name</key>
			<string>comment.tplpre</string>
		</dict>
		<key>double_qouted_line</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.single.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>"([^"]+?)"</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#percent_line</string>
				</dict>
			</array>
		</dict>
		<key>elif_statement</key>
		<dict>
			<key>match</key>
			<string>\belif\s+?</string>
			<key>name</key>
			<string>keyword.control.conditional.tplpre</string>
		</dict>
		<key>else_ADDM_statement</key>
		<dict>
			<key>match</key>
			<string>#ELSE\s+?</string>
			<key>name</key>
			<string>keyword.control.conditional.tplpre</string>
		</dict>
		<key>else_statement</key>
		<dict>
			<key>match</key>
			<string>\belse\s+?</string>
			<key>name</key>
			<string>keyword.control.conditional.tplpre</string>
		</dict>
		<key>end_for_statement</key>
		<dict>
			<key>match</key>
			<string>\bend\sfor;\s+?</string>
			<key>name</key>
			<string>keyword.control.tplpre</string>
		</dict>
		<key>end_if_ADDM_statement</key>
		<dict>
			<key>match</key>
			<string>#ENDIFADDM\s+?</string>
			<key>name</key>
			<string>keyword.control.conditional.tplpre</string>
		</dict>
		<key>end_if_statement</key>
		<dict>
			<key>match</key>
			<string>\bend\sif;\s+?</string>
			<key>name</key>
			<string>keyword.control.conditional.tplpre</string>
		</dict>
		<key>equal</key>
		<dict>
			<key>match</key>
			<string>\=</string>
			<key>name</key>
			<string>keyword.operator.assignment.tplpre</string>
		</dict>
		<key>for_statement</key>
		<dict>
			<key>match</key>
			<string>\bfor\s</string>
			<key>name</key>
			<string>keyword.control.tplpre</string>
		</dict>
		<key>if_ADDM_statement</key>
		<dict>
			<key>match</key>
			<string>#IFADDM</string>
			<key>name</key>
			<string>keyword.control.conditional.tplpre</string>
		</dict>
		<key>if_addm</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#if_ADDM_statement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#else_ADDM_statement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#end_if_ADDM_statement</string>
				</dict>
			</array>
		</dict>
		<key>if_statement</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.conditional.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:[^(end)])(if)(?:[^;\w])</string>
		</dict>
		<key>inference_functions</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.accessor.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.constant.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(inference)(\.)(associate|contributor|primary|relation|withdrawal|destruction)</string>
		</dict>
		<key>json_functions</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.accessor.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(json)(\.)(encode|decode)</string>
		</dict>
		<key>just_do</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\.)</string>
			<key>name</key>
			<string>punctuation.accessor.tplpre</string>
		</dict>
		<key>keywords_all</key>
		<dict>
			<key>match</key>
			<string>\b(aged|and|as|at|break|by|configuration|continue|created|default|desc|deleted|do|enumeration|exists|expand|explode|false|flags|from|has|in|is|locale|matches|modified|nodes|nodecount|none|not|on|or|order|out|overrides|processwith|relationship|removal|requires|search|show|step|stop|substring|subword|summary|tags|taxonomy|traverse|true|unconfirmed|where|with|void)\b</string>
			<key>name</key>
			<string>support.type.tplpre</string>
		</dict>
		<key>keywords_cmd</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(unix_cmd|windows_cmd)</string>
		</dict>
		<key>keywords_cmd_indentify_trigger</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(unix_cmd|windows_cmd|cmd|args)</string>
		</dict>
		<key>less</key>
		<dict>
			<key>match</key>
			<string>\&lt;</string>
			<key>name</key>
			<string>keyword.operator.tplpre</string>
		</dict>
		<key>less_equal</key>
		<dict>
			<key>match</key>
			<string>\&lt;\=</string>
			<key>name</key>
			<string>keyword.operator.tplpre</string>
		</dict>
		<key>lines</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#percent_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_TODO_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#qouted_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regexes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#double_qouted_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#square_brackets_line_word</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#square_brackets_line_int</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#all_keys</string>
				</dict>
			</array>
		</dict>
		<key>local_functions</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.accessor.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(local_functions|localFunctions)(\.)(\w+)</string>
		</dict>
		<key>log_functions</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(log\.(?:debug|info|warn|error|critical))</string>
		</dict>
		<key>mail_functions</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.accessor.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(mail)(\.)(send)</string>
		</dict>
		<key>metadata</key>
		<dict>
			<key>begin</key>
			<string>^\s{4}(metadata)\s+?$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^\s{4}(end\smetadata;)\s+?$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lines</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#if_addm</string>
				</dict>
			</array>
		</dict>
		<key>metadata_2</key>
		<dict>
			<key>begin</key>
			<string>^(metadata)\s+?$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(end\smetadata;)\s+?$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lines</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#if_addm</string>
				</dict>
			</array>
		</dict>
		<key>minus_decimal</key>
		<dict>
			<key>match</key>
			<string>\s\-\d+\s</string>
			<key>name</key>
			<string>constant.numeric.integer.tplpre</string>
		</dict>
		<key>model_SI_functions</key>
		<dict>
			<key>begin</key>
			<string>((model)(\.)(SoftwareInstance))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.accessor.tplpre</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.constant.tplpre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\;</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>disabled.tplpre</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#lines</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#all_controls</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regex</string>
				</dict>
			</array>
		</dict>
		<key>model_functions</key>
		<dict>
			<key>begin</key>
			<string>(model)(\.)(addContainment|setContainment|destroy|withdraw|setRemovalGroup|anchorRemovalGroup|suppressRemovalGroup|host|hosts|findPackages|addDisplayAttribute|removeDisplayAttribute|kind)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.accessor.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.constant.tplpre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\;</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>disabled.tplpre</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#lines</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#all_controls</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regex</string>
				</dict>
			</array>
		</dict>
		<key>model_rel_functions</key>
		<dict>
			<key>begin</key>
			<string>((model)(\.)(rel|uniquerel)(\.)(Communication|Containment|Dependency|Detail|HostContainment|HostedFile|HostedSoftware|Management|RelatedFile|SoftwareService|SoftwareContainment|StorageUse))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.accessor.tplpre</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.constant.tplpre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\;</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>disabled.tplpre</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#lines</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#all_controls</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regex</string>
				</dict>
			</array>
		</dict>
		<key>more</key>
		<dict>
			<key>match</key>
			<string>\&gt;</string>
			<key>name</key>
			<string>keyword.operator.tplpre</string>
		</dict>
		<key>more_equal</key>
		<dict>
			<key>match</key>
			<string>\&gt;\=</string>
			<key>name</key>
			<string>keyword.operator.tplpre</string>
		</dict>
		<key>number_functions</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.accessor.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.constant.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(number)(\.)(toChar|toText|range)</string>
		</dict>
		<key>overwiev</key>
		<dict>
			<key>begin</key>
			<string>^\s{4}(overview)\s+?$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^\s{4}(end\soverview;)\s+?$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
			</dict>
			<key>name</key>
			<string>overwiev.complex.tplpre</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tags_TKU</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords_all</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#if_addm</string>
				</dict>
			</array>
		</dict>
		<key>percent_line</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>%([^%]+)%</string>
			<key>name</key>
			<string>keyword.control.tplpre</string>
		</dict>
		<key>plus</key>
		<dict>
			<key>match</key>
			<string>\+</string>
			<key>name</key>
			<string>keyword.operator.assignment.tplpre</string>
		</dict>
		<key>qouted_line</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.single.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\'([^']+?)\'</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#percent_line</string>
				</dict>
			</array>
		</dict>
		<key>rdbms_functions</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.accessor.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(rdbms_functions)(\.)(oracle_ora_file_parser|perform_rdbms_sis_search|related_rdbms_sis_search|related_rdbms_sis_search_extended|oracle_net_service_name_search|dsn_rdbms_servers|parseJDBC|jdbc_search|find_db_server)</string>
		</dict>
		<key>regex</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(regex)\s+</string>
			<key>name</key>
			<string>regex.tplpre</string>
		</dict>
		<key>regex_2_lines</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(regex)</string>
			<key>name</key>
			<string>regex.tplpre</string>
		</dict>
		<key>regex_functions</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.accessor.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(regex)(\.)(extract|extractAll)</string>
		</dict>
		<key>regex_raw</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(raw)\s+('|")(\\\d+)('|")</string>
		</dict>
		<key>regexes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#regex_raw</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regex</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#content_raw</string>
				</dict>
			</array>
		</dict>
		<key>related_functions</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.accessor.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.constant.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(related)(\.)(detailContainer|host\b|hostingNode)</string>
		</dict>
		<key>removal</key>
		<dict>
			<key>begin</key>
			<string>^\s{4}(removal)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^\s{4}(end\sremoval;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
			</dict>
			<key>name</key>
			<string>constants.complex.tplpre</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#lines</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#all_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#all_controls</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#if_addm</string>
				</dict>
			</array>
		</dict>
		<key>simple_identifiers</key>
		<dict>
			<key>begin</key>
			<string>\b(identify)\s+(\w+)\s(\d+(?:\.\d+)+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.tplpre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(end\sidentify;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#lines</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords_cmd</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords_all</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regexes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords_cmd_indentify_trigger</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#if_addm</string>
				</dict>
			</array>
		</dict>
		<key>single_q</key>
		<dict>
			<key>match</key>
			<string>(\'\'){1}</string>
			<key>name</key>
			<string>comment.tplpre</string>
		</dict>
		<key>square_brackets_line_int</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\[(-?\d+)\]</string>
		</dict>
		<key>square_brackets_line_word</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\[(\w+[^\d+])\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#regex_2_lines</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#percent_line</string>
				</dict>
			</array>
		</dict>
		<key>tags</key>
		<dict>
			<key>comment</key>
			<string>Tags</string>
			<key>match</key>
			<string>\s+(tags)\s+(.*?);</string>
			<key>name</key>
			<string>constant.other.tplpre</string>
		</dict>
		<key>tags_TKU</key>
		<dict>
			<key>comment</key>
			<string>Tags TKU</string>
			<key>match</key>
			<string>(TKU_\d+_\d+_\d+)</string>
			<key>name</key>
			<string>constant.other.tplpre</string>
		</dict>
		<key>text_functions</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.accessor.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.constant.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(text)(\.)(lower|upper|toNumber|replace|join|split|strip|leftStrip|rightStrip|hash|ordinal)</string>
		</dict>
		<key>then_statement</key>
		<dict>
			<key>match</key>
			<string>\bthen\s+?</string>
			<key>name</key>
			<string>keyword.control.conditional.tplpre</string>
		</dict>
		<key>time_functions</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.accessor.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(time)(\.)(current|delta|parseLocal|parseUTC|formatLocal|formatUTC|toTicks|fromTicks)</string>
		</dict>
		<key>triggers</key>
		<dict>
			<key>begin</key>
			<string>^\s{4}(triggers)\s+?$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^\s{4}(end\striggers;)\s+?$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
			</dict>
			<key>name</key>
			<string>overwiev.complex.tplpre</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#lines</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#all_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#all_controls</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords_cmd_indentify_trigger</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#if_addm</string>
				</dict>
			</array>
		</dict>
		<key>var_assign</key>
		<dict>
			<key>match</key>
			<string>\:\=</string>
			<key>name</key>
			<string>keyword.operator.assignment.tplpre</string>
		</dict>
		<key>xpath_functions</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.tplpre</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.accessor.tplpre</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.tplpre</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(xpath)(\.)(evaluate|openDocument|closeDocument)</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.tplpre</string>
	<key>uuid</key>
	<string>f1aa2af1-00ed-4fa2-91f3-e9a19f9f4710</string>
</dict>
</plist>
